import { localizeCarbonScreenData } from './carbon-screen.i18n'
import type {
  CarbonScreenApi,
  CarbonScreenDashboard,
  CarbonScreenScopeDistributionSourceRow,
} from './carbon-screen.types'
import { CARBON_SCREEN_PRODUCT_DIALOG_PALETTE } from '@/lib/carbon-screen-chart-colors'

const SCOPE_DISTRIBUTION_ROWS: Array<CarbonScreenScopeDistributionSourceRow> = [
  {
    id: 'scope-row-001',
    category: '类别1:GHG直接排放和清除',
    subCategory: '移动燃烧源的排放',
    source: '商务车使用燃料',
    co2e: 14.3554319,
    share: 0.06,
  },
  {
    id: 'scope-row-002',
    category: '类别1:GHG直接排放和清除',
    subCategory: '工业过程排放和清除',
    source: '乙炔的燃烧',
    co2e: 0,
    share: 0,
  },
  {
    id: 'scope-row-003',
    category: '类别1:GHG直接排放和清除',
    subCategory: '来自人类活动的逸散排放',
    source: '二氧化碳灭火器的逸散',
    co2e: 0,
    share: 0,
  },
  {
    id: 'scope-row-004',
    category: '类别1:GHG直接排放和清除',
    subCategory: '来自人类活动的逸散排放',
    source: '化粪池的逸散',
    co2e: 21.5331478,
    share: 0.09,
  },
  {
    id: 'scope-row-005',
    category: '类别1:GHG直接排放和清除',
    subCategory: '来自人类活动的逸散排放',
    source: '使用R134a的空调制冷设备',
    co2e: 0,
    share: null,
  },
  {
    id: 'scope-row-006',
    category: '类别1:GHG直接排放和清除',
    subCategory: '来自人类活动的逸散排放',
    source: '使用R32的空调制冷设备',
    co2e: 0,
    share: null,
  },
  {
    id: 'scope-row-007',
    category: '类别1:GHG直接排放和清除',
    subCategory: '来自人类活动的逸散排放',
    source: '使用R410a的空调制冷设备',
    co2e: 0,
    share: null,
  },
  {
    id: 'scope-row-008',
    category: '类别1:GHG直接排放和清除',
    subCategory: '来自人类活动的逸散排放',
    source: '使用R410A的制冷机组',
    co2e: 0,
    share: null,
  },
  {
    id: 'scope-row-009',
    category: '类别2:输入能源产生的GHG间接排放',
    subCategory: '输入电力产生的间接排放',
    source: '市政用电',
    co2e: 2553.0643557,
    share: 10.38,
  },
  {
    id: 'scope-row-010',
    category: '类别2:输入能源产生的GHG间接排放',
    subCategory: '输入能源产生的间接排放',
    source: '外购蒸汽',
    co2e: 779.6930643,
    share: 3.17,
  },
  {
    id: 'scope-row-011',
    category: '类别3:运输产生的间接GHG排放',
    subCategory: '货物上游运输和配送产生的排放',
    source: '外购货物上游运输',
    co2e: 596.0220899,
    share: 2.42,
  },
  {
    id: 'scope-row-012',
    category: '类别3:运输产生的间接GHG排放',
    subCategory: '货物下游运输和配送产生的排放',
    source: '成品下游运输配送',
    co2e: 179.7917874,
    share: 0.73,
  },
  {
    id: 'scope-row-013',
    category: '类别4:组织所用产品产生的间接GHG排放',
    subCategory: '采购商品和服务',
    source: '组织所用产品采购',
    co2e: 20457.9945867,
    share: 83.15,
  },
]

const PRODUCT_RANKING_DIALOG: CarbonScreenDashboard['dialogs']['productRanking'] =
  {
    title: '产品碳足迹 - 男士商务西服套装',
    summary: {
      productName: '男士商务西服套装',
      productCode: 'BXN-SUIT-SET-001',
      gwpResult: 64.9996205,
      uncertainty: '-26.81% ~ 28.16%',
    },
    modelResult: {
      defaultDetailView: 'stage',
      palette: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE,
      methodResults: [
        {
          label: 'GWP100 - 温室气体',
          full: 'IPCC 2021 - climate change: total (excl. biogenic CO…',
          value: 49.5243134,
        },
        {
          label: 'GWP100 - 化石（除航空）',
          full: 'IPCC 2021 - climate change: fossil emissions (excl. ai…',
          value: 49.1186042,
        },
        {
          label: 'GWP100 - 生物',
          full: 'IPCC 2021 - climate change: biogenic (excl. CO2) - g…',
          value: 0.2845171,
        },
        {
          label: 'GWP100 - 土地',
          full: 'IPCC 2021 - climate change: direct land use change …',
          value: 0.1211921,
        },
        {
          label: 'GWP100 - 航空',
          full: 'IPCC 2021 - climate change: aircraft emissions - glo…',
          value: 0,
        },
      ],
      processUnits: [
        {
          id: 'wool-unit-001',
          name: '羊毛原料的生产',
          stage: '原材料获取',
          module: '原料的生产',
          percentage: 21,
          gwp: 10.400105814,
        },
        {
          id: 'wool-unit-002',
          name: '毛用活性染料的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 1.836735,
          gwp: 0.909630242,
        },
        {
          id: 'wool-unit-003',
          name: '酸性染料的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0,
          gwp: 0,
        },
        {
          id: 'wool-unit-004',
          name: '匀染剂的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 1.102041,
          gwp: 0.545778145,
        },
        {
          id: 'wool-unit-005',
          name: '纯碱的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0.367347,
          gwp: 0.181926048,
        },
        {
          id: 'wool-unit-006',
          name: '冰醋酸的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0.734694,
          gwp: 0.363852097,
        },
        {
          id: 'wool-unit-007',
          name: '双氧水的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 8.44898,
          gwp: 4.184299152,
        },
        {
          id: 'wool-unit-008',
          name: '保险粉的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0.367347,
          gwp: 0.181926048,
        },
        {
          id: 'wool-unit-009',
          name: '皂洗剂的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0.367347,
          gwp: 0.181926048,
        },
        {
          id: 'wool-unit-010',
          name: '柔软剂的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 2.571429,
          gwp: 1.273482339,
        },
        {
          id: 'wool-unit-011',
          name: '固色剂的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0,
          gwp: 0,
        },
        {
          id: 'wool-unit-012',
          name: '漂白助剂的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 0.734694,
          gwp: 0.363852097,
        },
        {
          id: 'wool-unit-013',
          name: '脱色助剂的生产',
          stage: '原材料获取',
          module: '辅料的生产',
          percentage: 1.469388,
          gwp: 0.727704194,
        },
        {
          id: 'wool-unit-014',
          name: 'PAC的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 3.926761,
          gwp: 1.94470121,
        },
        {
          id: 'wool-unit-015',
          name: 'PAM的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 0.095775,
          gwp: 0.047431736,
        },
        {
          id: 'wool-unit-016',
          name: '水软化剂（工业盐）的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 0.335211,
          gwp: 0.166011078,
        },
        {
          id: 'wool-unit-017',
          name: '聚铝的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 0.766197,
          gwp: 0.379453897,
        },
        {
          id: 'wool-unit-018',
          name: '硫酸（污水）的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 0.670423,
          gwp: 0.332022155,
        },
        {
          id: 'wool-unit-019',
          name: '中和剂（浓碱）的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 4.740845,
          gwp: 2.34787097,
        },
        {
          id: 'wool-unit-020',
          name: '次氯酸钠的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 2.15493,
          gwp: 1.067214076,
        },
        {
          id: 'wool-unit-021',
          name: '除臭剂的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 1.532394,
          gwp: 0.758907788,
        },
        {
          id: 'wool-unit-022',
          name: '絮凝剂的生产',
          stage: '原材料获取',
          module: '水处理化学品的生产',
          percentage: 2.777465,
          gwp: 1.375520368,
        },
        {
          id: 'wool-unit-023',
          name: '用电',
          stage: '生产制造',
          module: '能源使用',
          percentage: 9.476551,
          gwp: 4.693196657,
        },
        {
          id: 'wool-unit-024',
          name: '蒸汽',
          stage: '生产制造',
          module: '能源使用',
          percentage: 7.270802,
          gwp: 3.600814678,
        },
        {
          id: 'wool-unit-025',
          name: '天然气',
          stage: '生产制造',
          module: '能源使用',
          percentage: 1.252648,
          gwp: 0.620365077,
        },
        {
          id: 'wool-unit-026',
          name: '废水处理',
          stage: '生产制造',
          module: '废水处理',
          percentage: 8.068966,
          gwp: 3.996099757,
        },
        {
          id: 'wool-unit-027',
          name: '污泥处置',
          stage: '生产制造',
          module: '废水处理',
          percentage: 4.931034,
          gwp: 2.442060985,
        },
        {
          id: 'wool-unit-028',
          name: '包装袋',
          stage: '生产制造',
          module: '包装与入库',
          percentage: 8.357143,
          gwp: 4.138817607,
        },
        {
          id: 'wool-unit-029',
          name: '叉车作业',
          stage: '生产制造',
          module: '包装与入库',
          percentage: 4.642857,
          gwp: 2.299343135,
        },
      ],
    },
    analysis: {
      breakdowns: {
        stage: [
          {
            name: '原材料获取',
            value: 56,
            gwp: 27.733615502,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.raw,
          },
          {
            name: '生产制造',
            value: 44,
            gwp: 21.790697896,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturing,
          },
        ],
        module: [
          {
            name: '原料的生产',
            value: 21,
            gwp: 10.400105814,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.raw,
          },
          {
            name: '辅料的生产',
            value: 18,
            gwp: 8.91437641,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.rawLight,
          },
          {
            name: '水处理化学品的生产',
            value: 17,
            gwp: 8.419133278,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.transport,
          },
          {
            name: '能源使用',
            value: 18,
            gwp: 8.914376412,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturing,
          },
          {
            name: '废水处理',
            value: 13,
            gwp: 6.438160742,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturingLight,
          },
          {
            name: '包装与入库',
            value: 13,
            gwp: 6.438160742,
            color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.hazard,
          },
        ],
      },
      allMethodsData: [
        { name: '温室气体', raw: 56, manufacturing: 44, transport: 0 },
        { name: '土地利用', raw: 60, manufacturing: 40, transport: 0 },
        { name: '生物碳', raw: 54, manufacturing: 46, transport: 0 },
        {
          name: '化石（非航空）',
          raw: 57,
          manufacturing: 43,
          transport: 0,
        },
        { name: '航空', raw: 52, manufacturing: 48, transport: 0 },
      ],
      sensitivityData: [
        {
          name: '羊毛原料的生产',
          value: 18.42,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.raw,
        },
        {
          name: '用电',
          value: 5.96,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturing,
        },
        {
          name: '蒸汽',
          value: 4.31,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturingLight,
        },
        {
          name: '中和剂（浓碱）的生产',
          value: 1.34,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.transport,
        },
        {
          name: 'PAC的生产',
          value: 1.11,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.rawLight,
        },
      ],
      uncertaintyData: [
        {
          name: '羊毛原料的生产',
          value: 12.81,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.raw,
        },
        {
          name: '蒸汽',
          value: 6.24,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturingLight,
        },
        {
          name: '用电',
          value: 5.48,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.manufacturing,
        },
        {
          name: '中和剂（浓碱）的生产',
          value: 1.92,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.transport,
        },
        {
          name: '废水处理',
          value: 1.15,
          color: CARBON_SCREEN_PRODUCT_DIALOG_PALETTE.hazard,
        },
      ],
      monteCarlo: {
        uncertaintyRange: '-26.81% ~ 28.16%',
        nodes: [
          { name: '男士商务西服套装', mean: 64.9996, std: 6.4124 },
          { name: '羊毛原料的生产', mean: 10.4001, std: 1.4296 },
          { name: '用电', mean: 4.6932, std: 0.6758 },
          { name: '蒸汽', mean: 3.6008, std: 0.497 },
        ],
      },
      keyMetrics: {
        totalGwp: 49.5243134,
        uncertainty: '-26.81% ~ 28.16%',
        maxContributionStage: {
          name: '原材料获取',
          pct: 56,
        },
        topSources: [
          { name: '羊毛原料的生产', pct: 21 },
          { name: '用电', pct: 9.48 },
          { name: '双氧水的生产', pct: 8.45 },
        ],
        standard: 'ISO 14067:2018',
        scope: 'GWP100 · 从摇篮到大门',
      },
    },
  }

const DASHBOARD_DATA: CarbonScreenDashboard = {
  header: {
    title: '某某集团全景碳驾驶舱',
    siteOptions: [
      { value: 'factory-1', label: '某甲工厂' },
      { value: 'factory-2', label: '某乙工厂' },
      { value: 'factory-3', label: '某丙工厂' },
    ],
    yearOptions: [
      { value: '2025年', label: '2025年' },
      { value: '2024年', label: '2024年' },
      { value: '2023年', label: '2023年' },
    ],
    weather: {
      condition: '晴',
      temperatureRange: '2~8°C',
    },
  },
  metrics: [
    {
      id: 'total-emission',
      label: '总碳排量',
      value: 42000,
      unit: 'tCO2e',
    },
    {
      id: 'emission-target',
      label: '总碳排目标',
      value: 60000,
      unit: 'tCO2e',
    },
    {
      id: 'total-reduction',
      label: '总减排量',
      value: 12300,
      unit: 'tCO2e',
    },
    {
      id: 'reduction-target',
      label: '总减排目标',
      value: 20000,
      unit: 'tCO2e',
    },
    {
      id: 'emission-intensity',
      label: '碳排强度',
      value: 34.8,
      unit: 'tCO2e',
      decimals: 2,
    },
    {
      id: 'intensity-target',
      label: '目标碳排强度',
      value: 50,
      unit: 'tCO2e',
      decimals: 2,
    },
  ],
  grade: {
    label: '碳排水平',
    value: '优秀',
    description: '较行业平均碳排强度更优',
  },
  dialogs: {
    scopeDistribution: {
      title: '组织碳足迹 - 某甲工厂',
      summary: {
        totalEmission: 42000,
        unit: 'tCO2e',
        gwpVersion: 'AR5',
      },
      rows: [...SCOPE_DISTRIBUTION_ROWS],
    },
    productRanking: PRODUCT_RANKING_DIALOG,
  },
  charts: {
    scopeDistribution: [
      { name: '范围一', value: 20.77 },
      { name: '范围二', value: 10.23 },
      { name: '范围三', value: 69 },
    ],
    reductionProjectDistribution: [
      { name: '能源替代', value: 39.13 },
      { name: '工艺优化', value: 10.87 },
      { name: '管理措施', value: 15 },
      { name: '其他', value: 35 },
    ],
    productRanking: [
      { name: '男士商务西服套装', value: 64.9996205 },
      { name: '男士西服上衣', value: 41.0895289 },
      { name: '男士西服裤装', value: 23.9100915 },
      { name: '男士衬衫', value: 7.0017115 },
      { name: '户外T恤', value: 3.2174358 },
    ],
  },
}

export function createCarbonScreenMockApi(): CarbonScreenApi {
  return {
    getDashboard: () => localizeCarbonScreenData(DASHBOARD_DATA),
  }
}
